security:
  basic:
    enabled: false
    ignored: /**
server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: secondMicroservice
eureka:
  client:
    serviceUrl:
      #da cambiare su docker
      #defaultZone: ${EUREKA_HOST:http://eureka:8001/eureka/}
      defaultZone: ${EUREKA_HOST:http://localhost:8001/eureka/}
